### ISSUE TITLE
Incorrect temperature on Heru 200T EC over TCP/IP

### ISSUE THREAD

**Issue by Articate** [kjeet90/homey-ostberg-heru#13]
Firmware: 1.08 (newest is 1.09i - will try upgrading at some point)

On my Heru 200T EC over TCP/IP, in Homey my temperatures shows up as 1 2 2 2 2 instead of 14 20 21 15 20. It seems some devices report their temperatures in tenths of degrees (220 for 22) and others as degrees (22 for 22). Is this split between serial or TCP/IP, perhaps?

**Comment by kjeet90** [comment]
I haven't head about it from someone else, so I assume it might be due to old (or new?) firmware. Unfortunately it wasn't documentet in the modbus interface that it would report in 220 on my system, and hence not that it would report 22 on your system. I will probably have to add either manual setting or automated catch for this.

**Comment by kjeet90** [comment]
@Articate did you try to upgrade the firmware on the Heru unit? If so, did it fix it?

**Comment by Articate** [comment]
Thanks for following up. Haven't gotten around to it, but I'll try it right away!

**Comment by Articate** [comment]
I updated, and the temperature now reads correctly!

**Comment by kjeet90** [comment]
Lovely, thanks for testing! I'll close the issue and just require that people upgrade their unit firmware instead of making a "fix" for this then.
