### ISSUE TITLE
Extraction Fan alarm always on

### ISSUE THREAD

**Issue by Articate** [kjeet90/homey-ostberg-heru#14]
Despite my device saying no active alarms, it seems the Extraction Fan alarm is always on. My device says there's an active alarm, and that's the alarm that's returned.

**Comment by kjeet90** [comment]
Since we've already discussed this on the Homey Community forum, I'll just add the info here as well, in case other people only read it here.

I am also getting alarms on both Supply fan and Extract fan during normal operation, Östberg said that it could possibly a incorrect modbus configuration.

I might try to add a trigger on low/high setting for the alarms, so any incorrect trigger can be inverted by the device.

**Comment by kjeet90** [comment]
@Articate option to invert alarms in test version [here](https://homey.app/en-us/app/no.kjeet90.ostbergheru/%C3%96stberg-Heru/test) if you want to give it a test
